apiVersion: v1
kind: Service
metadata:
        name: radarr-svc
        labels:
          name: radarr-media-tv
          app: radarr
        namespace: media
spec:
  selector:
     app: radarr
  ports:
   - name: radarr
     port: 80
     targetPort: 7878
