apiVersion: v1
kind: Service
metadata:
  name: plex-udp-svc
  labels:
    name: plex-udp-svc
    app: plex
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: plex
spec:
  selector:
     app: plex
  ports:
   - name: plex32410
     protocol: UDP
     port: 32410
     targetPort: 32410
   - name: plex32412
     protocol: UDP
     port: 32412
     targetPort: 32412
   - name: plex32413
     protocol: UDP
     port: 32413
     targetPort: 32413
   - name: plex32414
     protocol: UDP
     port: 32414
     targetPort: 32414
  type: LoadBalancer
  loadBalancerIP: 192.168.1.246
  externalTrafficPolicy: Local
