apiVersion: v1
kind: Service
metadata:
  name: plex-tcp-svc
  labels:
    name: plex-tcp-svc
    app: plex
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: plex
spec:
  selector:
    app: plex
  ports:
  - name: plex32400
    protocol: TCP
    port: 32400
    targetPort: 32400
  - name: plex3005
    protocol: TCP
    port: 3005
    targetPort: 3005
  - name: plex8324
    protocol: TCP
    port: 8324
    targetPort: 8324
  - name: plex32469
    protocol: TCP
    port: 32469
    targetPort: 32469
  type: LoadBalancer
  loadBalancerIP: 192.168.1.246
  externalTrafficPolicy: Local
