apiVersion: v1
kind: Service
metadata:
        name: sonarr-svc
        labels:
          name: sonarr-media-tv
          app: sonarr
        namespace: media
spec:
  selector:
     app: sonarr
  ports:
   - name: sonarr
     port: 80
     targetPort: 8989
