apiVersion: v1
kind: Service
metadata:
        name: procurement-svc
        labels:
          name: procurement
          app: procurement
        namespace: media
spec:
  selector:
     app: procurement
  ports:
   - name: sab
     port: 80
     targetPort: 8080
   - name: radarr
     port: 81
     targetPort: 5076
