apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: dev-db-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: dev-nfs
  selector:
     matchLabels:
       usage: dev-nfs-db
  volumeMode: Filesystem

