apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: "tdarr-data"
spec:
  storageClassName: "manual"
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: "20Gi"
