apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfs-media-anime
  namespace: media
  labels:
    usage: media-nfs-anime
spec: 
  capacity:
    storage: 79Ti
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - auto
    - defaults
    - nofail
    - 0 0
  nfs:
    path: /mnt/user/Anime
    server: tardis10g
