apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-anime-claim
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 79Ti
  storageClassName: media-nfs
  selector:
     matchLabels:
       usage: media-nfs-anime


