apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-tv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 79Ti
  storageClassName: media-nfs
  selector:
     matchLabels:
       usage: media-nfs
  volumeMode: Filesystem

