apiVersion: v1
kind: PersistentVolume
metadata: 
  name: plex-local
  namespace: media
  labels:
    usage: media-plex-local
spec: 
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: plex-local
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/plex/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
           - perseus
