apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-plex-local-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: plex-local
  selector:
     matchLabels:
       usage: media-plex-local


